"""Deterministic writers: verified Markdown -> docx / pdf / pptx, calcs -> xlsx.

`render_markdown` is the only entry point the adapters use. It verifies citations
first and refuses to produce an Office file from a draft with errors unless forced,
in which case the footer is stamped UNVERIFIED.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from ..util import now_iso
from ..verify import verify_file
from ..workspace import Workspace
from . import model as _model

FORMATS = ("docx", "pdf", "pptx")


@dataclass
class RenderResult:
    ok: bool
    message: str
    path: Path | None = None


def render_markdown(
    ws: Workspace, md_path: str, fmt: str, out: str | None = None, template: str | None = None, force: bool = False
) -> RenderResult:
    fmt = fmt.lower().lstrip(".")
    if fmt not in FORMATS:
        return RenderResult(False, f"Unknown format '{fmt}'. Use one of {', '.join(FORMATS)} (xlsx: use export_xlsx).")
    src = ws.abspath(md_path)
    if not src.exists():
        return RenderResult(False, f"Markdown file not found: {md_path}")
    report = verify_file(ws, src)
    if report.status == "FAIL" and not force:
        return RenderResult(False, "Refusing to render: citation verification failed.\n" + report.to_text())
    stamp = "UNVERIFIED DRAFT" if report.status == "FAIL" else f"Citations verified ({report.status})"
    footer = f"{ws.name} · generated by RnD {now_iso()[:10]} · {stamp} · source: {ws.rel(src)}"
    doc = _model.parse(src.read_text(encoding="utf-8"))
    from ..api import resolve_output_path

    target = resolve_output_path(ws, out, src.stem, "." + fmt)
    tpl = ws.abspath(template) if template else None
    if tpl is not None and not tpl.exists():
        return RenderResult(False, f"Template not found: {template}")
    if fmt == "docx":
        from .word import render
    elif fmt == "pptx":
        from .slides import render
    else:
        from .pdf import render
    render(ws, doc, target, tpl, footer)
    msg = (
        f"Wrote {ws.rel(target)} ({len(doc.sources)} sources, verification {report.status}"
        + (f", {len(report.errors)} errors — UNVERIFIED" if report.errors else "")
        + ")"
    )
    warn = [i for i in report.issues if i.level == "warn"]
    if warn:
        msg += "\n" + "\n".join(f"  WARN {w.message}" for w in warn[:5])
    return RenderResult(True, msg, target)
