"""Saved calcs -> a formatted .xlsx with native charts and a Provenance sheet.

Values are written as typed numbers/dates (never as text), so the workbook can be
used for further analysis; the Provenance sheet records the SQL and source files of
every sheet so each figure can be reproduced.
"""

from __future__ import annotations

import datetime as dt
from typing import Any

from ..data.tables import load_calc
from ..util import now_iso, sql_ident
from ..workspace import Workspace


def _value(v: Any) -> Any:
    """Calcs store dates as ISO strings; turn them back into real Excel dates."""
    if isinstance(v, str) and len(v) >= 10 and v[4] == "-" and v[7] == "-":
        try:
            return dt.date.fromisoformat(v) if len(v) == 10 else dt.datetime.fromisoformat(v)
        except ValueError:
            return v
    return v


def export_calcs(
    ws: Workspace, calc_ids: list[int], out_path, sheet_names: list[str] | None = None, chart: str | None = None
) -> str:
    import openpyxl
    from openpyxl.chart import BarChart, LineChart, PieChart, Reference
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    wb = openpyxl.Workbook()
    wb.remove(wb.active)
    prov_rows = []
    head_fill = PatternFill("solid", fgColor="DDE6F0")
    for n, cid in enumerate(calc_ids):
        calc = load_calc(ws, cid)
        name = (sheet_names[n] if sheet_names and n < len(sheet_names) else f"calc_{cid}")[:31]
        name = "".join(ch for ch in name if ch not in "[]:*?/\\") or f"calc_{cid}"
        sh = wb.create_sheet(name)
        sh.append(calc["columns"])
        for c in sh[1]:
            c.font = Font(bold=True)
            c.fill = head_fill
        for row in calc["rows"]:
            sh.append([_value(v) for v in row])
        for i, col in enumerate(calc["columns"], start=1):
            values = [col] + [str(r[i - 1]) for r in calc["rows"][:200]]
            sh.column_dimensions[get_column_letter(i)].width = min(60, max(10, max(len(v) for v in values) + 2))
            for cell in sh[get_column_letter(i)][1:]:
                if isinstance(cell.value, float):
                    cell.number_format = "#,##0.00##"
                elif isinstance(cell.value, (dt.date, dt.datetime)):
                    cell.number_format = "yyyy-mm-dd"
        sh.freeze_panes = "A2"
        if calc["rows"]:
            sh.auto_filter.ref = f"A1:{get_column_letter(len(calc['columns']))}{len(calc['rows']) + 1}"
        numeric = [
            i
            for i, _ in enumerate(calc["columns"])
            if calc["rows"] and all(isinstance(r[i], (int, float)) and not isinstance(r[i], bool) for r in calc["rows"])
        ]
        if chart and numeric and len(calc["rows"]) >= 2:
            ys = [i for i in numeric if i != 0]
            if ys:
                ch = {"line": LineChart, "pie": PieChart}.get(chart, BarChart)()
                if isinstance(ch, BarChart):
                    ch.type = "bar" if chart == "bar" else "col"
                ch.title = name
                n_rows = len(calc["rows"]) + 1
                for i in ys[:1] if chart == "pie" else ys:
                    ch.add_data(Reference(sh, min_col=i + 1, min_row=1, max_row=n_rows), titles_from_data=True)
                ch.set_categories(Reference(sh, min_col=1, min_row=2, max_row=n_rows))
                ch.width, ch.height = 18, 9
                sh.add_chart(ch, f"{get_column_letter(len(calc['columns']) + 2)}2")
        prov_rows.append(
            [
                name,
                f"calc:{cid}",
                calc["created"],
                calc["row_count"],
                ", ".join(calc.get("source_files", [])),
                calc["sql"],
            ]
        )
    prov = wb.create_sheet("Provenance")
    prov.append(["sheet", "calc", "computed", "rows", "source files", "sql"])
    for c in prov[1]:
        c.font = Font(bold=True)
        c.fill = head_fill
    for r in prov_rows:
        prov.append(r)
    for col, w in zip("ABCDEF", (18, 10, 20, 8, 50, 90)):
        prov.column_dimensions[col].width = w
    for row in prov.iter_rows(min_row=2):
        row[5].alignment = Alignment(wrap_text=True, vertical="top")
    prov.append([])
    prov.append([f"Generated by RnD from workspace '{ws.name}' on {now_iso()}. Re-run the SQL to reproduce."])
    wb.properties.title = sql_ident(ws.name)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(str(out_path))
    return f"Wrote {ws.rel(out_path)} with {len(calc_ids)} sheet(s) + Provenance."
